### ISSUE TITLE
Add support for multiple scripts

### ISSUE THREAD

**Issue by shivam-tripathi** [momocow/webpack-tampermonkey#1]
I think by adding multiple entry points in webpack we can build multiple scripts. But there needs to be a way to specify script specific headers, as all scripts may not be having same headers.

**Comment by momocow** [comment]
Thanks for suggestion. I'll think about it. :)

**Comment by momocow** [comment]
Maybe the comment is a little bit too late.... but!
If you have come out with any solutions, PR is always welcome.

Sorry for inconvenience, since I am not a full-time and keep working on another project these days.
Maybe I'll come back to this package in the future, but not now.

**Comment by shivam-tripathi** [comment]
@momocow Hey, no inconvenience at all, in fact a great starting point for working with tampermonkey scripts. 
I was browsing through tools which could help me for a project I was supposed to work on in the coming months - when I stumbled across your tool :)
The project is still WIP, and when I'll get to the tampermonkey script part, I'll make sure to try and find a solution to the wonderful tool you've developed! :)
Again, thanks for being a open sourceror :D

**Comment by momocow** [comment]
Finally I'm back to this project again and pick up a totally different solution for integrating userscripts and Webpack. That is, make the package a **Webpack plugin** instead of a project starter kit to leave everything flexible and configurable for developers.

This changes also solves the issue for multiple entries, as anyone who is interesting in this can take a look at the test for [multiple entries](https://github.com/momocow/webpack-tampermonkey/tree/dev/test/fixtures/multi-entry).

@shivam-tripathi I'll close this issues (a year after it was opened 😂). Feel free to reopen it or file a new one if there is anything unsolved.

**Comment by momocow** [comment]
The plugin is now available as [`webpack-tampermonkey@2.0.0` on NPM](https://www.npmjs.com/package/webpack-tampermonkey).
